spring:
  application:
    name: deharri-api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: deharri-user-mgmt-service
            uri: lb://deharri-user-mgmt-service
            predicates:
              - Path=/ums/**
            filters:
              - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
